name: QualityMap_Back_End
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Teste
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
    